# Site settings
title:          AI
description:    "Nischay Chauhan, Blog, Machine Learning, Deep Learning, AI, NischayChauhan.github.io"

url:            "https://nischaychauhan.github.io"

# Author
author:
  name:         Nischay Chauhan
  url:          https://nischaychauhan.github.io/portfolio
  email:        chauhannischay164@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
